### PR TITLE
Better Docusaurus Support

### LINKED ISSUE #41: undefined wrapper on code blocks
Reproducible on docusaurus across all the code blocks, probably related to the remark plugin?

image

### LINKED ISSUE #50: Line highlightings are not working for non-twoslash code blocks

### PR DESCRIPTION
**Pull request by frencojobs**
This PR does -

- [x] Allow not only one preset but all presets with supported plugins such as `@docusaurus/content-docs`
- [x] Outdate the requirement of `MDXComponents` override
- [x] Close #41 
- [x] Add docusaurus's default copy-to-clipboard button which is better in a11y and i18n support
- [x] Include default twoslash CSS which is override-able
- [x] Support `title` argument in the code fence as default preset does
- [x] Close #50
- [x] Discard errors, queries, completions when copying to clipboard, also don't discard new lines

### CODE REVIEW

File: packages/remark-shiki-twoslash/src/index.ts [hunk 1]
```diff
@@ -35,6 +45,9 @@ function getHTML(code: string, lang: string, metaString: string, highlighters: H
       return renderCodeToHTML(code, lang, metaString.split(" "), { themeName }, highlighter, twoslash)
     })
     results = output.join("\n")
+    if (highlighters.length > 1 && wrapFragments) {
+      results = `<div class="shiki-twoslash-fragment">${results}</div>`
+    }
```
Comment (orta) [inline packages/remark-shiki-twoslash/src/index.ts:50]: I see, nice thinking

File: packages/remark-shiki-twoslash/src/index.ts [hunk 2]
```diff
@@ -7,11 +7,21 @@ import visit from "unist-util-visit"
 import { addIncludes, replaceIncludesInCode } from "./includes"
 import { cachedTwoslashCall } from "./caching"
 
+export type Settings = UserConfigSettings & {
+  wrapFragments?: true
+}
```
Comment (orta) [inline packages/remark-shiki-twoslash/src/index.ts:12]: I think this should probably be added in `shiki-twoslash` so that all the config types are in one place ( even though I totally see the value in having it here)

File: packages/remark-shiki-twoslash/src/index.ts (hunk 1 above)
Comment (frencojobs) [reply packages/remark-shiki-twoslash/src/index.ts:50]: yes, I switched that div with a React fragment when rendering back in React

**Comment by orta** [comment]
Structurally seems sound to me 👍🏻

**Comment by frencojobs** [comment]
Hi @orta, can you review this please. I've added a default CSS based on your CSS but modified it to use the CSS variables from docusaurus. I've added examples in the `examples/docusaurus`, you can see the results there.

I've also made it so that the fence parser will parse the title and pass it through the meta and render with a `div.code-title` tag. For convenience, the `pre` tag will have a class `.with-title` whenever there's a title in the code block. But I've made them optional and to show up if and only if there's the title in the fence so all the tests should just pass OK. It won't affect any existing stuffs.

This makes the user require nothing but a preset and lets them have a much nicer out-of-the-box experience. No overriding or CSS should be required to make it work.

We might have to update the documentations before deploy though, but I'm afraid you'll be better at that. Take your time. Byee.

**Comment by frencojobs** [comment]
This is out of scope for this PR but added a fix to #50 since it was on the way.

**Comment by frencojobs** [comment]
Found a bug!

File: packages/docusaurus-preset-shiki-twoslash/docusaurus-theme-shiki-twoslash/theme/CodeBlock/styles.css [hunk 3]
```diff
@@ -0,0 +1,290 @@
...
+
+/* Respect people's wishes to not have animations */
+@media (prefers-reduced-motion: reduce) {
+  data-lsp,
+  pre .code-container > a,
+  pre.shiki div.dim,
+  pre.shiki div.highlight::before {
+    transition: none;
+  }
+}
```
Comment (orta) [inline packages/docusaurus-preset-shiki-twoslash/docusaurus-theme-shiki-twoslash/theme/CodeBlock/styles.css:296]: This is the only thing which I'd like to see improvements on, it's not blocking though.

Can we automate copying the twoslash CSS [from this file](https://github.com/shikijs/twoslash/blob/main/packages/shiki-twoslash/style.css) (`/packages/shiki-twoslash/style.css`) into the bottom of this file during a deploy? I'll _definitely_ forget to update this CSS as things change.

File: packages/shiki-twoslash/src/parseCodeFenceInfo.ts [hunk 4]
```diff
@@ -34,7 +38,14 @@ export function parseCodeFenceInfo(lang: string, fullMetaString: string) {
...
 
-  return { languageName, meta }
+  if (fullMetaString.match(titlePattern)) {
+    meta.title = fullMetaString.match(titlePattern)?.[2] ?? ""
+  }
+
+  return {
+    languageName,
+    meta,
+  }
```
Comment (orta) [inline packages/shiki-twoslash/src/parseCodeFenceInfo.ts:48]: Seems reasonable to me, this will need to be documented somewhere in the shiki-twoslash README too

**Review by orta — APPROVED** [review]

File: packages/shiki-twoslash/src/parseCodeFenceInfo.ts (hunk 4 above)
Comment (orta) [reply packages/shiki-twoslash/src/parseCodeFenceInfo.ts:48]: I'll do this. Let me know when you're happy

File: packages/docusaurus-preset-shiki-twoslash/docusaurus-theme-shiki-twoslash/theme/CodeBlock/styles.css (hunk 3 above)
Comment (frencojobs) [reply packages/docusaurus-preset-shiki-twoslash/docusaurus-theme-shiki-twoslash/theme/CodeBlock/styles.css:296]: I don't think it's gonna work though. My commit just a min ago even modify the default CSS soo much it's basically not the same. Things had to be done to make it work with docusaurus's default infima CSS variables and paddings.

File: packages/shiki-twoslash/src/parseCodeFenceInfo.ts (hunk 4 above)
Comment (frencojobs) [reply packages/shiki-twoslash/src/parseCodeFenceInfo.ts:48]: I'm finished. Feel free to take on. Was about to go to bed so good luck.

File: packages/docusaurus-preset-shiki-twoslash/docusaurus-theme-shiki-twoslash/theme/CodeBlock/styles.css (hunk 3 above)
Comment (orta) [reply packages/docusaurus-preset-shiki-twoslash/docusaurus-theme-shiki-twoslash/theme/CodeBlock/styles.css:296]: OK, then we'll have to think of this as potential tech debt in that we accept that they could get out of sync 👍🏻

**Comment by orta** [comment]
Will give a last read and deploy after a walk
