### PR TITLE
Use Fenceparser

### LINKED ISSUE #77: Twoslash will be incorrectly run on certain scenarios
<p align="center">

</p>

This part is problematic because it will assume ` ```ts title="twoslash"` as twoslash code. Just leaving it up this issue as a reminder, this will be fixed together with the `parseCodeFenceInfo` refactor.

### PR DESCRIPTION
**Pull request by frencojobs**
Closes #77

### CODE REVIEW

**Comment by frencojobs** [comment]
Hi @orta. Help pls. I don't know what's wrong with my pnpm but when I installed the `fenceparser` package, it updates the lock file breaking the links. It not only add the `fencerparser` to the `pnpm-lock.yaml` but also turns every `link:../packages` into versions. I couldn't even test a thing because it just won't work. So I didn't even commit the lockfile. Could you please update the lock file for me so I can at least test or build things? Thanks.

**Comment by orta** [comment]
I think this is my fault, trying running `node scripts/syncVersions.js`  and re-run

File: packages/remark-shiki-twoslash/src/index.ts [hunk 1]
```diff
@@ -53,14 +61,14 @@ function getHTML(
  * Runs twoslash across an AST node, switching out the text content, and lang
  * and adding a `twoslash` property to the node.
  */
-export const runTwoSlashOnNode = (code: string, lang: string, meta: string, settings: UserConfigSettings = {}) => {
+export const runTwoSlashOnNode = (code: string, { lang, meta }: Fence, settings: UserConfigSettings = {}) => {
```
Comment (orta) [inline packages/remark-shiki-twoslash/src/index.ts:64]: Reasonable, note this is a major semver bump (for example this will break the typescript website tests (which is fine))

File: packages/shiki-twoslash/package.json [hunk 2]
```diff
@@ -35,6 +35,7 @@
   },
   "devDependencies": {
     "@types/jest": "^25.1.3",
+    "fenceparser": "^1.1.0",
```
Comment (orta) [inline packages/shiki-twoslash/package.json:38]: I imagine this wants to be in "dependencies" instead?

File: packages/shiki-twoslash/src/utils.ts [hunk 3]
```diff
@@ -1,3 +1,7 @@
+import type { parse } from "fenceparser"
+
+export type Meta = NonNullable<ReturnType<typeof parse>>
```
Comment (orta) [inline packages/shiki-twoslash/src/utils.ts:3]: Nice

File: packages/shiki-twoslash/package.json (hunk 2 above)
Comment (frencojobs) [reply packages/shiki-twoslash/package.json:38]: No no, shiki-twoslash only needs it for the type. Parsing is done only once in the remark package.

**Comment by orta** [comment]
I fixed main and merged that in instead

**Comment by frencojobs** [comment]
Great! Now only one test is failing. Nice.

File: packages/remark-shiki-twoslash/src/includes.ts [hunk 4]
```diff
@@ -34,7 +33,7 @@ export const replaceIncludesInCode = (_map: Map<string, string>, code: string) =
     const replaceWith = _map.get(key)
 
     if (!replaceWith) {
-      const msg = `Could not find an includes with the key: '${key}'.\nThere is: ${[..._map.keys()]}.`
+      const msg = `Could not find an include with the key: '${key}'.\nThere is: ${Array.from(_map.keys())}.`
```
Comment (frencojobs) [inline packages/remark-shiki-twoslash/src/includes.ts:36]: Otherwise, it'll only show up as `[object Map Iterator]
`

**Review by orta — APPROVED** [review]
